config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"
  resources :users, only: [:show,:new,:create] do
    member do
      get :likes
    end
  end
  
  
  resources :posts, only: [:new,:create, :destroy,:show] do
    member do
      get :mentions
      get :mentioned
    end
  end
  
  resources :items, only: [:new]
  resources :likes, only:[:create, :destroy]
  resources :comments, only: [:create, :destroy, :show, :edit, :new]
  resources :comment_relationships, only:[:create, :destroy]
  
  get "rankings/like", to: "rankings#like"
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :posts
  
  has_many :comments
  
  has_many :likes
  has_many :favorites, through: :likes, source: :post
  
  
  def favorite(other_post)
    unless self.id == other_post.user_id
      self.likes.find_or_create_by(post_id: other_post.id)
    end
    
  end
  
  def unfavorite(other_post)
    like = self.likes.find_by(post_id: other_post.id)
    like.destroy if like
  end
  
  def favorite?(other_post)
    self.favorites.include?(other_post)
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :likes]
  
  def show
    @user = current_user
    @post = current_user.posts.build
    @posts = current_user.posts.order("created_at DESC").page(params[:page])
    counts(@user)
    
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to(@user)
      
    else
      flash.now[:danger] =  'ユーザの登録に失敗しました。'
      render(:new)
    end
  end
  
  def likes
    @user = current_user
    @favorite_posts = current_user.favorites.order("created_at DESC").page(params[:page])
    counts(@user)
    
  end  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/users/likes.html.erb
<div class="row">
  <aside class="col-lg-2 col-lg-offset-1 col-md-2 col-md-offset-1 col-sm-3 col-sm-offset-4 col-xs-3 col-xs-offset-4">
    <div class="user-profile">
      <div class="icon text-center">
        <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
      </div>
      <div class="name text-center">
        <h1><%= @user.name %></h1>
      </div>
    </div>
  </aside>
  <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-xs-12 col-xs-offset-0 col-sm-10 col-sm-offset-1">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Posts <span class="badge"><%= @count_posts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(likes_user_path(@user)) %>"><%= link_to likes_user_path(@user) do %>Likes <span class="badge"><%= @count_likes %></span><% end %></li>
      
    </ul>
    <%= render 'posts/posts', posts: @favorite_posts %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-2 col-xs-8 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-lg-2 col-lg-offset-1 col-md-2 col-md-offset-1 col-sm-3 col-sm-offset-4 col-xs-3 col-xs-offset-4">
    <div class="user-profile">
      <div class="icon text-center">
        <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
      </div>
      <div class="name text-center">
        <h1><%= @user.name %></h1>
      </div>
    </div>
  </aside>
  <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-xs-12 col-xs-offset-0 col-sm-10 col-sm-offset-1">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Posts <span class="badge"><%= @count_posts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(likes_user_path(@user)) %>"><%= link_to likes_user_path(@user) do %>Likes <span class="badge"><%= @count_likes %></span><% end %></li>
      
    </ul>
    <%= render 'posts/posts', posts: @posts %>
  </div>
</div>