config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"
  resources :users, only: [:show,:new,:create] do
    member do
      get :likes
    end
  end
  
  
  resources :posts, only: [:new,:create, :destroy,:show] do
    member do
      get :mentions
      get :mentioned
    end
  end
  
  resources :items, only: [:new]
  resources :likes, only:[:create, :destroy]
  resources :comments, only: [:create, :destroy, :show, :edit, :new]
  resources :comment_relationships, only:[:create, :destroy]
  
  get "rankings/like", to: "rankings#like"
end

app/models/item.rb
class Item < ApplicationRecord
  validates :code, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
  validates :image_url, presence: true, length: { maximum: 255 }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user_logged_in

  
  def new
    @items = []
    
    @keyword = params[:keyword]
    
    if @keyword.present?
      results = RakutenWebService::Ichiba::Item.search({
        keyword: @keyword,
        imageFlag: 1,
        hits: 20,
      })
      
      
      results.each do |result|
        item = Item.new(read(result))
        @items << item
      end
      
    end
    
  end
  
  
  private
  
  def read(result)
    code = result['itemCode']
    name = result['itemName']
    url = result['itemUrl']
    image_url = result['mediumImageUrls'].first['imageUrl'].gsub('?_ex=128x128', '')

    return {
      code: code,
      name: name,
      url: url,
      image_url: image_url,
    }
  end  
end

app/views/items/_items.html.erb
<% if items %>
  <div class="row">
    <% items.each do |item| %>
      <div class="item">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <img src="<%= item.image_url %>" alt="" >
            </div>
            <div class="panel-body text-center">
                          
              
              <%= form_tag(new_post_path, method: :get, class: "form-inline") do %>
                <%= hidden_field_tag(:url, item.url) %>
                <%= hidden_field_tag(:image_url, item.image_url) %>
                <%= submit_tag("この画像を選ぶ", class: 'btn btn-success btn-lg') %>
              <% end %>
              
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/items/new.html.erb
<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(new_item_path, method: :get, class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :keyword, @keyword, class: 'form-control input-lg', placeholder: "キーワードを入力", size: 40 %>
        </div>
        <%= submit_tag 'このアニメについてレビューする', class: 'btn btn-success btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'items', items: @items %>