config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"
  resources :users, only: [:show,:new,:create] do
    member do
      get :likes
    end
  end
  
  
  resources :posts, only: [:new,:create, :destroy,:show] do
    member do
      get :mentions
      get :mentioned
    end
  end
  
  resources :items, only: [:new]
  resources :likes, only:[:create, :destroy]
  resources :comments, only: [:create, :destroy, :show, :edit, :new]
  resources :comment_relationships, only:[:create, :destroy]
  
  get "rankings/like", to: "rankings#like"
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2018 AnimeChanel.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-left" href="/"><img src="/images/logo1.png" alt="AnimeChanel"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
            <%= link_to(new_item_path) do %>
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
              レビューを追加
            <% end %>
            
          </li>
          
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
                ランキング
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'いいねランキング', rankings_like_path %></li>
              </ul>
            </li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="gravater">
                <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
              </span>
              <%= current_user.name%>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to('マイページ', user_path(current_user) ) %>
              </li>
              <li role="seperator" class="divider"></li>
              <li>
                <%= link_to("ログアウト", logout_path, method: :delete)%>
              </li>
            </ul>
            
          </li>
        
        <% else %>
          <li><%=link_to('新規登録',signup_path)%></li>
          <li><%= link_to('ログイン', login_path) %></li>
          
        <% end %>
      </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>AnimeChannel</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
      

    </div>

    <%= render 'layouts/footer' %>
  </body>
  
  
  
</html>